[book]
title = "RLG Documentation"
authors = ["Sebastian Rousseau"]
language = "en"
src = "docs"

[build]
build-dir = "target/book"

[output.html]
git-repository-url = "https://github.com/sebastienrousseau/rlg"
edit-url-template = "https://github.com/sebastienrousseau/rlg/edit/main/docs/{path}"
no-section-label = true
