[package]
authors = ["RustLogs Contributors"]
categories = [
    "asynchronous",
    "development-tools::debugging",
    "development-tools",
    "data-structures",
]
description = """
    A Rust library that implements application-level logging with a simple,
    readable output format.
"""
documentation = "https://docs.rs/rlg"
edition = "2021"
exclude = ["/.git/*", "/.github/*", "/.gitignore", "/.vscode/*"]
homepage = "https://rustlogs.com/"
keywords = ["debugging", "log", "rlg", "logging", "tracing"]
license = "MIT OR Apache-2.0"
name = "rlg"
repository = "https://github.com/sebastienrousseau/rlg/"
rust-version = "1.71.1"
version = "0.0.2"
include = [
    "../../LICENSE-APACHE",
    "../../LICENSE-MIT",
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/examples/**",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[workspace]
members = ["xtask"]

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"

[dependencies]
dtt = "0.0.5"
vrd = "0.0.4"
tokio = { version = "1.35.0", features = ["full"] }

[dev-dependencies]
criterion = "0.5.1"

[lib]
crate-type = ["lib"]
name = "rlg"
path = "src/lib.rs"

[features]
default = []

[package.metadata.docs.rs]
all-features = true

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1        # Compile crates one after another so the compiler can optimize better
debug = false            # Disable debug information
debug-assertions = false # Disable debug assertions
incremental = false      # Disable incremental compilation
lto = true               # Enables link to optimizations
opt-level = "s"          # Optimize for binary size
overflow-checks = false  # Disable overflow checks
panic = "abort"          # Strip expensive panic clean-up logic
rpath = false            # Disable rpath
strip = "symbols"        # Automatically strip symbols from the binary.

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false
