#!/usr/bin/env bash
# Compose a GitHub release page in the portfolio format (AGENTS.md §3):
#
#   ## Highlights ⭐️      hand-written, from docs/releases/v<VERSION>.md
#   ## What's Changed     generated by GitHub's generate-notes API
#   ## New Contributors   generated, only when there are any
#   ## Checksums          SHA-256 of every file in ASSET_DIR
#   **Full Changelog**    compare URL from the previous tag
#
# Usage: scripts/compose-release-notes.sh <tag> <previous-tag> <asset-dir>
# Needs `gh` authenticated for the repository (GH_REPO or the checkout's
# remote). Writes the notes to stdout.
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

tag=${1:?tag, e.g. v0.0.13}
previous=${2:?previous tag, e.g. v0.0.12}
assets=${3:?directory holding the release assets}
version=${tag#v}
highlights_file="docs/releases/v${version}.md"
[ -f "$highlights_file" ] || {
  echo "missing $highlights_file" >&2
  exit 1
}
repo=${GH_REPO:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}

# The Highlights section, from its heading up to the next heading.
highlights=$(awk '/^## Highlights/{on=1} on && /^## / && !/^## Highlights/{exit} on' \
  "$highlights_file")
[ -n "$highlights" ] || {
  echo "no Highlights section in $highlights_file" >&2
  exit 1
}

# What's Changed (and New Contributors), as GitHub generates them.
generated=$(gh api "repos/${repo}/releases/generate-notes" \
  -f tag_name="$tag" -f previous_tag_name="$previous" --jq .body)
changed=$(printf '%s\n' "$generated" |
  awk '/^\*\*Full Changelog\*\*/{exit} /^## /{on=1} on')
[ -n "$changed" ] || changed="## What's Changed"

sums=$(cd "$assets" && find . -maxdepth 1 -type f ! -name SHA256SUMS -print |
  sed 's|^\./||' | LC_ALL=C sort | xargs sha256sum)

fence='```'
printf '%s\n\n%s\n\n## Checksums\n\n%stext\n%s\n%s\n\n**Full Changelog**: https://github.com/%s/compare/%s...%s\n' \
  "$highlights" "$changed" "$fence" "$sums" "$fence" "$repo" "$previous" "$tag"
