name: 🧪 Audit

on:
  push:
    branches: [main, "feat/*"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  call-commons-audit:
    name: Run Master Audit
    uses: sebastienrousseau/commons/.github/workflows/audit.yml@main
