name: 🧪 Audit

on:
  push:
    branches: [main, "feat/*"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # Weekly at midnight on Monday

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit
      - name: Audit vulnerabilities
        run: cargo audit
