name: 📶 Coverage

on:
  push:
    branches: [main, "feat/*"]
  pull_request:
    branches: [main]

jobs:
  call-commons-coverage:
    name: Run Master Coverage
    uses: sebastienrousseau/commons/.github/workflows/coverage.yml@main
    secrets: inherit
