name: 🧪 Document

on:
  push:
    branches: [main]

jobs:
  doc:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Generate docs
        run: |
          RUSTDOCFLAGS="--cfg docsrs" cargo doc --no-deps --all-features --workspace
          echo '<html><head><meta http-equiv="refresh" content="0; url=rlg/index.html"></head><body></body></html>' > target/doc/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          commit_message: "docs: deploy documentation [skip ci]"
